# Generated by Django 3.2.5 on 2021-07-13 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMessage",
            fields=[
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="Team Messages",
                        max_length=100,
                        populate_from=["message_title"],
                        unique=True,
                    ),
                ),
                ("message_title", models.CharField(max_length=50)),
                ("message", models.TextField(max_length=500)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Message",
                "verbose_name_plural": "Team Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("US/Arizona", "US/Arizona"),
                            ("US/Central", "US/Central"),
                            ("US/Eastern", "US/Eastern"),
                            ("US/Mountain", "US/Mountain"),
                            ("US/Pacific", "US/Pacific"),
                        ],
                        default="US/Pacific",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile Information",
                "verbose_name_plural": "Profiles",
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="event slug field",
                        max_length=100,
                        populate_from=[
                            "title",
                            "start_datetime__month",
                            "start_datetime__day",
                            "start_datetime__year",
                        ],
                        unique=True,
                    ),
                ),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("released", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("under_contract", "Under Contract"),
                            ("approved", "Approved"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("online_live", "Online - Live"),
                            ("online_pre_recorded", "Online - Pre-Recorded"),
                            ("online_hybrid", "Online - Hybrid"),
                            ("in_person", "In Person"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_notes", models.TextField(blank=True, max_length=500)),
                ("team_member_notes", models.TextField(blank=True, max_length=500)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_datetime"], name="ess_app_eve_start_d_3a4f8b_idx"
            ),
        ),
    ]
